apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
  name: cilium.v1.8.6
  namespace: cilium
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: CiliumConfig
      name: ciliumconfigs.cilium.io
      version: v1alpha1
  description: Cilium - eBPF-based Networking, Security, and Observability
  displayName: Cilium
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resourceNames:
          - cilium
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          verbs:
          - create
          - get
          - patch
          - update
          - delete
          - list
          - watch
        - apiGroups:
          - cilium.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - get
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          - pods/status
          - pods/finalizers
          verbs:
          - get
          - list
          - watch
          - update
          - delete
        - apiGroups:
          - ""
          resources:
          - nodes
          - nodes/status
          verbs:
          - get
          - list
          - watch
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - namespaces
          - services
          - endpoints
          - componentstatuses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - discovery.k8s.io
          resources:
          - endpointslices
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - get
          - list
          - watch
        serviceAccountName: cilium-olm
      deployments:
      - name: cilium-olm
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: cilium-olm
          template:
            metadata:
              labels:
                name: cilium-olm
            spec:
              containers:
              - command:
                - /usr/local/bin/helm-operator
                - run
                - --watches-file=watches.yaml
                - --enable-leader-election
                - --leader-election-id=cilium-olm
                - --zap-devel
                env:
                - name: WATCH_NAMESPACE
                  value: cilium
                image: registry.connect.redhat.com/isovalent/cilium-olm:27b1cb89d26212eedd054c21cbafc0af6aef2e42-v1.8.6
                name: operator
                ports:
                - containerPort: 9443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 100m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 100Mi
                volumeMounts:
                - mountPath: /tmp
                  name: tmp
              hostNetwork: true
              serviceAccount: cilium-olm
              terminationGracePeriodSeconds: 10
              tolerations:
              - operator: Exists
              volumes:
              - emptyDir: {}
                name: tmp
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - cilium.io
          resources:
          - ciliumconfigs
          - ciliumconfigs/status
          verbs:
          - list
        - apiGroups:
          - cilium.io
          resourceNames:
          - cilium
          resources:
          - ciliumconfigs
          - ciliumconfigs/status
          - ciliumconfigs/finalizers
          verbs:
          - get
          - patch
          - update
          - watch
          - list
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          - configmaps
          - secrets
          - services
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          verbs:
          - '*'
        serviceAccountName: cilium-olm
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - networking
  - security
  - observability
  - eBPF
  links:
  - name: Cilium Homepage
    url: https://cilium.io/
  maturity: stable
  provider:
    name: Isovalent
  version: 1.8.6
