---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium
  annotations:
    # node selector is required to make cilium-operator run on control plane nodes
    openshift.io/node-selector: ""
  labels:
    name: cilium
    # run level sets priority for Cilium to be deployed prior to other components
    openshift.io/run-level: "0"
    # enable cluster logging for Cilium namespace
    openshift.io/cluster-logging: "true"
    # enable cluster monitoring for Cilium namespace
    openshift.io/cluster-monitoring: "true"
---
apiVersion: cilium.io/v1alpha1
kind: CiliumConfig
metadata:
  name: cilium
  namespace: cilium
spec:
  config:
    ipam: "cluster-pool"
    bpfMasquerade: false
  global:
    nativeRoutingCIDR: "10.128.0.0/14"
    endpointRoutes: {enabled: true}
    cni:
      binPath: "/var/lib/cni/bin"
      confPath: "/var/run/multus/cni/net.d"
    ipam:
      operator:
        clusterPoolIPv4PodCIDR: "10.128.0.0/14"
        clusterPoolIPv4MaskSize: "23"
    prometheus: 
      serviceMonitor: {enabled: false}
