apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cilium-olm
  namespace: cilium
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cilium-olm
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cilium.v1.9.0-rc3
