apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cilium-olm-cilium-olm
rules:
- apiGroups:
  - ""
  resourceNames:
  - cilium
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - create
  - get
  - patch
  - update
  - delete
  - list
  - watch
