apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cilium-olm-cilium-olm
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - cilium.io
  resources:
  - ciliumconfigs
  - ciliumconfigs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io/v1
  resourceNames:
  - cilium
  - cilium-operator
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
