# permissions for end users to edit cilia.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cilium-editor-role
rules:
- apiGroups:
  - cilium.io
  resources:
  - cilia
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cilium.io
  resources:
  - cilia/status
  verbs:
  - get
