# permissions for end users to view ciliumconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ciliumconfig-viewer
rules:
- apiGroups:
  - cilium.io
  resources:
  - ciliumconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cilium.io
  resources:
  - ciliumconfigs/status
  verbs:
  - get
