apiVersion: cilium.io/v1alpha1
kind: CiliumConfig
metadata:
  name: cilium
  namespace: cilium
spec:
  config:
    ipam: "cluster-pool"
  global:
    nativeRoutingCIDR: "10.128.0.0/14"
    endpointRoutes: {enabled: true}
    cni:
      binPath: "/var/lib/cni/bin"
      confPath: "/var/run/multus/cni/net.d"
    ipam:
      operator:
        clusterPoolIPv4PodCIDR: "10.128.0.0/14"
        clusterPoolIPv4MaskSize: "23"
    prometheus:
      serviceMonitor: {enabled: false}
