apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cilium-olm
  name: cilium-olm
  namespace: cilium
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cilium-olm
  template:
    metadata:
      labels:
        name: cilium-olm
    spec:
      containers:
      - command:
        - /usr/local/bin/helm-operator
        - run
        - --watches-file=watches.yaml
        - --enable-leader-election
        - --leader-election-id=cilium-olm
        - --zap-devel
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.connect.redhat.com/isovalent/cilium-olm:df0f1a45dbbfa7f19d8ba995861730000c877f02-v1.9.6
        name: operator
        ports:
        - containerPort: 9443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 150Mi
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      hostNetwork: true
      serviceAccount: cilium-olm
      terminationGracePeriodSeconds: 10
      tolerations:
      - operator: Exists
      volumes:
      - emptyDir: {}
        name: tmp
