apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cilium-olm
  name: cilium-olm
  namespace: cilium-olm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cilium-olm
  template:
    metadata:
      labels:
        name: cilium-olm
    spec:
      containers:
      - command:
        - /usr/local/bin/helm-operator
        - run
        - --watches-file=watches.yaml
        - --enable-leader-election
        - --leader-election-id=cilium-olm
        - --zap-devel
        env:
        - name: WATCH_NAMESPACE
          value: cilium
        image: docker.io/errordeveloper/cilium-olm.v1.9.0-rc1:65902cf7caf514552a60aac1dd7c01c48570150f-dev
        name: operator
        ports:
        - containerPort: 9443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      hostNetwork: true
      serviceAccount: cilium-olm
      terminationGracePeriodSeconds: 10
      tolerations:
      - operator: Exists
      volumes:
      - emptyDir: {}
        name: tmp
